### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by randomcamel** [randomcamel/terrachef#1]
- [x] Allow user to specify `:plan` vs. `:apply` and make that useful.
- [x] Integration testing (e.g. actually running the `terraform_execute` resource).
- [ ] Package up for consumption.
- [x] Full and unit-tested top-level `provisioner` support.
- [x] Full and unit-tested top-level `module` support.
- [ ] More `terraform` subcommands as resource actions. Possibilities:
  - [ ]  **destroy** - Destroy Terraform-managed infrastructure
  - [ ]  **get** -  Download and install modules for the configuration
  - [x]  **graph** -  Create a visual graph of Terraform resources
  - [ ]  **init** -  Initializes Terraform configuration from a module
  - [ ]  **output** -  Read an output from a state file
  - [ ]  **push** -  Upload this Terraform module to Atlas to run
  - [ ]  **refresh** -  Update local state file against real resources
  - [ ]  **remote** -  Configure remote state storage
  - [ ]  **show** -  Inspect Terraform state or plan
  - [ ]  **taint** -  Manually mark a resource for recreation
- [x] Better/any `.tfstate` management.
- [ ] Build some verified real-world examples.
- [x] Make sure we can do the nested hashes of e.g. [AWS Security Groups](https://terraform.io/docs/providers/aws/r/security_group.html).
- [ ] Make it run outside Chris's environment of having both Docker and AWS configured.

**Comment by randomcamel** [comment]
Toy project, EOLing since no one uses it. =)
